version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgrespw"
      POSTGRES_DB: "play_highlight"
    ports:
      - "5432:5432"
    volumes:
      - ./data/database:/var/lib/postgresql/data
  nestjs-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./data/backend:/usr/src/app/data
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - postgres
  react-app:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./data/backend:/usr/share/nginx/html/videos
    restart: unless-stopped
    depends_on:
      - nestjs-app
